name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: # 添加手动触发
    
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      # 不使用ZJU-Turing的插件
      # - name: Install TuringPlugins
      #   run: |
      #     git clone https://github.com/ZJU-Turing/TuringPlugins.git
      #     cd TuringPlugins
      #     pip install -e .
      #     cd ..
      - run: mkdocs gh-deploy --force